FROM gcr.io/distroless/cc-debian12:nonroot

ARG TARGETARCH

COPY binaries/${TARGETARCH}/tb-server /usr/local/bin/tb-server

ENV TB_HOST=0.0.0.0
ENV TB_PORT=8080

EXPOSE 8080

USER nonroot

CMD ["tb-server"]
